#include <stdio.h>
int main() {
    long long i = 0;

    {
        static double x_1 = -1;
        i = 1;
        printf("%lld\n", i);
        printf("%f\n", x_1);
        static double x_2 = +0.0;
        i = 2;
        printf("%lld\n", i);
        printf("%f\n", x_2);
        static double x_3 = -0.0;
        i = 3;
        printf("%lld\n", i);
        printf("%f\n", x_3);
        static double x_4 = -0.1 - 0.2;
        i = 4;
        printf("%lld\n", i);
        printf("%f\n", x_4);
        static double x_5 = -1.0;
        i = 5;
        printf("%lld\n", i);
        printf("%f\n", x_5);
        static double x_6 = -1.0 / 3.0;
        i = 6;
        printf("%lld\n", i);
        printf("%f\n", x_6);
        static double x_7 = -10.2349961;
        i = 7;
        printf("%lld\n", i);
        printf("%f\n", x_7);
        static double x_8 = -32434324234;
        i = 8;
        printf("%lld\n", i);
        printf("%f\n", x_8);
        static double x_9 = 0.0;
        i = 9;
        printf("%lld\n", i);
        printf("%f\n", x_9);
        static double x_10 = 0.1 + 0.2;
        i = 10;
        printf("%lld\n", i);
        printf("%f\n", x_10);
        static double x_11 = 1.0;
        i = 11;
        printf("%lld\n", i);
        printf("%f\n", x_11);
        static double x_12 = 1.0 / 3.0;
        i = 12;
        printf("%lld\n", i);
        printf("%f\n", x_12);
        static double x_13 = 2432423422341;
        i = 13;
        printf("%lld\n", i);
        printf("%f\n", x_13);
        static double x_14 = 5.89999961;
        i = 14;
        printf("%lld\n", i);
        printf("%f\n", x_14);

        static double x_15 = -1, x_16 = +0.0, x_17 = -0.0, x_18 = -0.1 - 0.2, x_19 = -1.0, x_20 = -1.0 / 3.0, x_21 = -10.2349961, x_22 = -32434324234, x_23 = 0.0, x_24 = 0.1 + 0.2, x_25 = 1.0, x_26 = 1.0 / 3.0, x_27 = 2432423422341, x_28 = 5.89999961;

        i = 15;
        printf("%lld\n", i);
        printf("%f\n", x_15);
        i = 16;
        printf("%lld\n", i);
        printf("%f\n", x_16);
        i = 17;
        printf("%lld\n", i);
        printf("%f\n", x_17);
        i = 18;
        printf("%lld\n", i);
        printf("%f\n", x_18);
        i = 19;
        printf("%lld\n", i);
        printf("%f\n", x_19);
        i = 20;
        printf("%lld\n", i);
        printf("%f\n", x_20);
        i = 21;
        printf("%lld\n", i);
        printf("%f\n", x_21);
        i = 22;
        printf("%lld\n", i);
        printf("%f\n", x_22);
        i = 23;
        printf("%lld\n", i);
        printf("%f\n", x_23);
        i = 24;
        printf("%lld\n", i);
        printf("%f\n", x_24);
        i = 25;
        printf("%lld\n", i);
        printf("%f\n", x_25);
        i = 26;
        printf("%lld\n", i);
        printf("%f\n", x_26);
        i = 27;
        printf("%lld\n", i);
        printf("%f\n", x_27);
        i = 28;
        printf("%lld\n", i);
        printf("%f\n", x_28);
    }
}
