# SPDX-FileCopyrightText: Copyright (c) 2021-2022 Polystat.org
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    ".clang-format",
    ".gitattributes",
    ".gitignore",
    "**/.clang-format",
    "**/*.c",
    "**/*.cff",
    "**/*.eo",
    "**/*.json",
    "**/*.md",
    "**/*.txt",
    "**/*.xml",
    "**/*.yml",
    "Dockerfile",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2021-2022 Polystat.org"
SPDX-License-Identifier = "MIT"
