long int var768;
long int var769 = 1;
static long int var770;
static long int var771 = 1;
extern long int var772;
extern long int var773 = 1;
const long int var774;
const long int var775 = 1;
static const long int var776;
static const long int var777 = 1;
extern const long int var778;
extern const long int var779 = 1;
volatile long int var780;
volatile long int var781 = 1;
static volatile long int var782;
static volatile long int var783 = 1;
extern volatile long int var784;
extern volatile long int var785 = 1;
const volatile long int var786;
const volatile long int var787 = 1;
static const volatile long int var788;
static const volatile long int var789 = 1;
extern const volatile long int var790;
extern const volatile long int var791 = 1;
inline long int var792;
inline long int var793 = 1;
static inline long int var794;
static inline long int var795 = 1;
extern inline long int var796;
extern inline long int var797 = 1;
const inline long int var798;
const inline long int var799 = 1;
static const inline long int var800;
static const inline long int var801 = 1;
extern const inline long int var802;
extern const inline long int var803 = 1;
volatile inline long int var804;
volatile inline long int var805 = 1;
static volatile inline long int var806;
static volatile inline long int var807 = 1;
extern volatile inline long int var808;
extern volatile inline long int var809 = 1;
const volatile inline long int var810;
const volatile inline long int var811 = 1;
static const volatile inline long int var812;
static const volatile inline long int var813 = 1;
extern const volatile inline long int var814;
extern const volatile inline long int var815 = 1;

void main() {}
