unsigned short int var384;
unsigned short int var385 = 1;
static unsigned short int var386;
static unsigned short int var387 = 1;
extern unsigned short int var388;
extern unsigned short int var389 = 1;
const unsigned short int var390;
const unsigned short int var391 = 1;
static const unsigned short int var392;
static const unsigned short int var393 = 1;
extern const unsigned short int var394;
extern const unsigned short int var395 = 1;
volatile unsigned short int var396;
volatile unsigned short int var397 = 1;
static volatile unsigned short int var398;
static volatile unsigned short int var399 = 1;
extern volatile unsigned short int var400;
extern volatile unsigned short int var401 = 1;
const volatile unsigned short int var402;
const volatile unsigned short int var403 = 1;
static const volatile unsigned short int var404;
static const volatile unsigned short int var405 = 1;
extern const volatile unsigned short int var406;
extern const volatile unsigned short int var407 = 1;
inline unsigned short int var408;
inline unsigned short int var409 = 1;
static inline unsigned short int var410;
static inline unsigned short int var411 = 1;
extern inline unsigned short int var412;
extern inline unsigned short int var413 = 1;
const inline unsigned short int var414;
const inline unsigned short int var415 = 1;
static const inline unsigned short int var416;
static const inline unsigned short int var417 = 1;
extern const inline unsigned short int var418;
extern const inline unsigned short int var419 = 1;
volatile inline unsigned short int var420;
volatile inline unsigned short int var421 = 1;
static volatile inline unsigned short int var422;
static volatile inline unsigned short int var423 = 1;
extern volatile inline unsigned short int var424;
extern volatile inline unsigned short int var425 = 1;
const volatile inline unsigned short int var426;
const volatile inline unsigned short int var427 = 1;
static const volatile inline unsigned short int var428;
static const volatile inline unsigned short int var429 = 1;
extern const volatile inline unsigned short int var430;
extern const volatile inline unsigned short int var431 = 1;

void main() {}
