unsigned long var864;
unsigned long var865 = 1;
static unsigned long var866;
static unsigned long var867 = 1;
extern unsigned long var868;
extern unsigned long var869 = 1;
const unsigned long var870;
const unsigned long var871 = 1;
static const unsigned long var872;
static const unsigned long var873 = 1;
extern const unsigned long var874;
extern const unsigned long var875 = 1;
volatile unsigned long var876;
volatile unsigned long var877 = 1;
static volatile unsigned long var878;
static volatile unsigned long var879 = 1;
extern volatile unsigned long var880;
extern volatile unsigned long var881 = 1;
const volatile unsigned long var882;
const volatile unsigned long var883 = 1;
static const volatile unsigned long var884;
static const volatile unsigned long var885 = 1;
extern const volatile unsigned long var886;
extern const volatile unsigned long var887 = 1;
inline unsigned long var888;
inline unsigned long var889 = 1;
static inline unsigned long var890;
static inline unsigned long var891 = 1;
extern inline unsigned long var892;
extern inline unsigned long var893 = 1;
const inline unsigned long var894;
const inline unsigned long var895 = 1;
static const inline unsigned long var896;
static const inline unsigned long var897 = 1;
extern const inline unsigned long var898;
extern const inline unsigned long var899 = 1;
volatile inline unsigned long var900;
volatile inline unsigned long var901 = 1;
static volatile inline unsigned long var902;
static volatile inline unsigned long var903 = 1;
extern volatile inline unsigned long var904;
extern volatile inline unsigned long var905 = 1;
const volatile inline unsigned long var906;
const volatile inline unsigned long var907 = 1;
static const volatile inline unsigned long var908;
static const volatile inline unsigned long var909 = 1;
extern const volatile inline unsigned long var910;
extern const volatile inline unsigned long var911 = 1;

void main() {}
