signed int var528;
signed int var529 = 1;
static signed int var530;
static signed int var531 = 1;
extern signed int var532;
extern signed int var533 = 1;
const signed int var534;
const signed int var535 = 1;
static const signed int var536;
static const signed int var537 = 1;
extern const signed int var538;
extern const signed int var539 = 1;
volatile signed int var540;
volatile signed int var541 = 1;
static volatile signed int var542;
static volatile signed int var543 = 1;
extern volatile signed int var544;
extern volatile signed int var545 = 1;
const volatile signed int var546;
const volatile signed int var547 = 1;
static const volatile signed int var548;
static const volatile signed int var549 = 1;
extern const volatile signed int var550;
extern const volatile signed int var551 = 1;
inline signed int var552;
inline signed int var553 = 1;
static inline signed int var554;
static inline signed int var555 = 1;
extern inline signed int var556;
extern inline signed int var557 = 1;
const inline signed int var558;
const inline signed int var559 = 1;
static const inline signed int var560;
static const inline signed int var561 = 1;
extern const inline signed int var562;
extern const inline signed int var563 = 1;
volatile inline signed int var564;
volatile inline signed int var565 = 1;
static volatile inline signed int var566;
static volatile inline signed int var567 = 1;
extern volatile inline signed int var568;
extern volatile inline signed int var569 = 1;
const volatile inline signed int var570;
const volatile inline signed int var571 = 1;
static const volatile inline signed int var572;
static const volatile inline signed int var573 = 1;
extern const volatile inline signed int var574;
extern const volatile inline signed int var575 = 1;

void main() {}
