unsigned short var336;
unsigned short var337 = 1;
static unsigned short var338;
static unsigned short var339 = 1;
extern unsigned short var340;
extern unsigned short var341 = 1;
const unsigned short var342;
const unsigned short var343 = 1;
static const unsigned short var344;
static const unsigned short var345 = 1;
extern const unsigned short var346;
extern const unsigned short var347 = 1;
volatile unsigned short var348;
volatile unsigned short var349 = 1;
static volatile unsigned short var350;
static volatile unsigned short var351 = 1;
extern volatile unsigned short var352;
extern volatile unsigned short var353 = 1;
const volatile unsigned short var354;
const volatile unsigned short var355 = 1;
static const volatile unsigned short var356;
static const volatile unsigned short var357 = 1;
extern const volatile unsigned short var358;
extern const volatile unsigned short var359 = 1;
inline unsigned short var360;
inline unsigned short var361 = 1;
static inline unsigned short var362;
static inline unsigned short var363 = 1;
extern inline unsigned short var364;
extern inline unsigned short var365 = 1;
const inline unsigned short var366;
const inline unsigned short var367 = 1;
static const inline unsigned short var368;
static const inline unsigned short var369 = 1;
extern const inline unsigned short var370;
extern const inline unsigned short var371 = 1;
volatile inline unsigned short var372;
volatile inline unsigned short var373 = 1;
static volatile inline unsigned short var374;
static volatile inline unsigned short var375 = 1;
extern volatile inline unsigned short var376;
extern volatile inline unsigned short var377 = 1;
const volatile inline unsigned short var378;
const volatile inline unsigned short var379 = 1;
static const volatile inline unsigned short var380;
static const volatile inline unsigned short var381 = 1;
extern const volatile inline unsigned short var382;
extern const volatile inline unsigned short var383 = 1;

void main() {}
