signed long int var816;
signed long int var817 = 1;
static signed long int var818;
static signed long int var819 = 1;
extern signed long int var820;
extern signed long int var821 = 1;
const signed long int var822;
const signed long int var823 = 1;
static const signed long int var824;
static const signed long int var825 = 1;
extern const signed long int var826;
extern const signed long int var827 = 1;
volatile signed long int var828;
volatile signed long int var829 = 1;
static volatile signed long int var830;
static volatile signed long int var831 = 1;
extern volatile signed long int var832;
extern volatile signed long int var833 = 1;
const volatile signed long int var834;
const volatile signed long int var835 = 1;
static const volatile signed long int var836;
static const volatile signed long int var837 = 1;
extern const volatile signed long int var838;
extern const volatile signed long int var839 = 1;
inline signed long int var840;
inline signed long int var841 = 1;
static inline signed long int var842;
static inline signed long int var843 = 1;
extern inline signed long int var844;
extern inline signed long int var845 = 1;
const inline signed long int var846;
const inline signed long int var847 = 1;
static const inline signed long int var848;
static const inline signed long int var849 = 1;
extern const inline signed long int var850;
extern const inline signed long int var851 = 1;
volatile inline signed long int var852;
volatile inline signed long int var853 = 1;
static volatile inline signed long int var854;
static volatile inline signed long int var855 = 1;
extern volatile inline signed long int var856;
extern volatile inline signed long int var857 = 1;
const volatile inline signed long int var858;
const volatile inline signed long int var859 = 1;
static const volatile inline signed long int var860;
static const volatile inline signed long int var861 = 1;
extern const volatile inline signed long int var862;
extern const volatile inline signed long int var863 = 1;

void main() {}
