unsigned long long int var1200;
unsigned long long int var1201 = 1;
static unsigned long long int var1202;
static unsigned long long int var1203 = 1;
extern unsigned long long int var1204;
extern unsigned long long int var1205 = 1;
const unsigned long long int var1206;
const unsigned long long int var1207 = 1;
static const unsigned long long int var1208;
static const unsigned long long int var1209 = 1;
extern const unsigned long long int var1210;
extern const unsigned long long int var1211 = 1;
volatile unsigned long long int var1212;
volatile unsigned long long int var1213 = 1;
static volatile unsigned long long int var1214;
static volatile unsigned long long int var1215 = 1;
extern volatile unsigned long long int var1216;
extern volatile unsigned long long int var1217 = 1;
const volatile unsigned long long int var1218;
const volatile unsigned long long int var1219 = 1;
static const volatile unsigned long long int var1220;
static const volatile unsigned long long int var1221 = 1;
extern const volatile unsigned long long int var1222;
extern const volatile unsigned long long int var1223 = 1;
inline unsigned long long int var1224;
inline unsigned long long int var1225 = 1;
static inline unsigned long long int var1226;
static inline unsigned long long int var1227 = 1;
extern inline unsigned long long int var1228;
extern inline unsigned long long int var1229 = 1;
const inline unsigned long long int var1230;
const inline unsigned long long int var1231 = 1;
static const inline unsigned long long int var1232;
static const inline unsigned long long int var1233 = 1;
extern const inline unsigned long long int var1234;
extern const inline unsigned long long int var1235 = 1;
volatile inline unsigned long long int var1236;
volatile inline unsigned long long int var1237 = 1;
static volatile inline unsigned long long int var1238;
static volatile inline unsigned long long int var1239 = 1;
extern volatile inline unsigned long long int var1240;
extern volatile inline unsigned long long int var1241 = 1;
const volatile inline unsigned long long int var1242;
const volatile inline unsigned long long int var1243 = 1;
static const volatile inline unsigned long long int var1244;
static const volatile inline unsigned long long int var1245 = 1;
extern const volatile inline unsigned long long int var1246;
extern const volatile inline unsigned long long int var1247 = 1;

void main() {}
