signed short var192;
signed short var193 = 1;
static signed short var194;
static signed short var195 = 1;
extern signed short var196;
extern signed short var197 = 1;
const signed short var198;
const signed short var199 = 1;
static const signed short var200;
static const signed short var201 = 1;
extern const signed short var202;
extern const signed short var203 = 1;
volatile signed short var204;
volatile signed short var205 = 1;
static volatile signed short var206;
static volatile signed short var207 = 1;
extern volatile signed short var208;
extern volatile signed short var209 = 1;
const volatile signed short var210;
const volatile signed short var211 = 1;
static const volatile signed short var212;
static const volatile signed short var213 = 1;
extern const volatile signed short var214;
extern const volatile signed short var215 = 1;
inline signed short var216;
inline signed short var217 = 1;
static inline signed short var218;
static inline signed short var219 = 1;
extern inline signed short var220;
extern inline signed short var221 = 1;
const inline signed short var222;
const inline signed short var223 = 1;
static const inline signed short var224;
static const inline signed short var225 = 1;
extern const inline signed short var226;
extern const inline signed short var227 = 1;
volatile inline signed short var228;
volatile inline signed short var229 = 1;
static volatile inline signed short var230;
static volatile inline signed short var231 = 1;
extern volatile inline signed short var232;
extern volatile inline signed short var233 = 1;
const volatile inline signed short var234;
const volatile inline signed short var235 = 1;
static const volatile inline signed short var236;
static const volatile inline signed short var237 = 1;
extern const volatile inline signed short var238;
extern const volatile inline signed short var239 = 1;

void main() {}
