char var0;
char var1 = 1;
static char var2;
static char var3 = 1;
extern char var4;
extern char var5 = 1;
const char var6;
const char var7 = 1;
static const char var8;
static const char var9 = 1;
extern const char var10;
extern const char var11 = 1;
volatile char var12;
volatile char var13 = 1;
static volatile char var14;
static volatile char var15 = 1;
extern volatile char var16;
extern volatile char var17 = 1;
const volatile char var18;
const volatile char var19 = 1;
static const volatile char var20;
static const volatile char var21 = 1;
extern const volatile char var22;
extern const volatile char var23 = 1;
inline char var24;
inline char var25 = 1;
static inline char var26;
static inline char var27 = 1;
extern inline char var28;
extern inline char var29 = 1;
const inline char var30;
const inline char var31 = 1;
static const inline char var32;
static const inline char var33 = 1;
extern const inline char var34;
extern const inline char var35 = 1;
volatile inline char var36;
volatile inline char var37 = 1;
static volatile inline char var38;
static volatile inline char var39 = 1;
extern volatile inline char var40;
extern volatile inline char var41 = 1;
const volatile inline char var42;
const volatile inline char var43 = 1;
static const volatile inline char var44;
static const volatile inline char var45 = 1;
extern const volatile inline char var46;
extern const volatile inline char var47 = 1;

void main() {}
