unsigned long int var912;
unsigned long int var913 = 1;
static unsigned long int var914;
static unsigned long int var915 = 1;
extern unsigned long int var916;
extern unsigned long int var917 = 1;
const unsigned long int var918;
const unsigned long int var919 = 1;
static const unsigned long int var920;
static const unsigned long int var921 = 1;
extern const unsigned long int var922;
extern const unsigned long int var923 = 1;
volatile unsigned long int var924;
volatile unsigned long int var925 = 1;
static volatile unsigned long int var926;
static volatile unsigned long int var927 = 1;
extern volatile unsigned long int var928;
extern volatile unsigned long int var929 = 1;
const volatile unsigned long int var930;
const volatile unsigned long int var931 = 1;
static const volatile unsigned long int var932;
static const volatile unsigned long int var933 = 1;
extern const volatile unsigned long int var934;
extern const volatile unsigned long int var935 = 1;
inline unsigned long int var936;
inline unsigned long int var937 = 1;
static inline unsigned long int var938;
static inline unsigned long int var939 = 1;
extern inline unsigned long int var940;
extern inline unsigned long int var941 = 1;
const inline unsigned long int var942;
const inline unsigned long int var943 = 1;
static const inline unsigned long int var944;
static const inline unsigned long int var945 = 1;
extern const inline unsigned long int var946;
extern const inline unsigned long int var947 = 1;
volatile inline unsigned long int var948;
volatile inline unsigned long int var949 = 1;
static volatile inline unsigned long int var950;
static volatile inline unsigned long int var951 = 1;
extern volatile inline unsigned long int var952;
extern volatile inline unsigned long int var953 = 1;
const volatile inline unsigned long int var954;
const volatile inline unsigned long int var955 = 1;
static const volatile inline unsigned long int var956;
static const volatile inline unsigned long int var957 = 1;
extern const volatile inline unsigned long int var958;
extern const volatile inline unsigned long int var959 = 1;

void main() {}
