unsigned char var96;
unsigned char var97 = 1;
static unsigned char var98;
static unsigned char var99 = 1;
extern unsigned char var100;
extern unsigned char var101 = 1;
const unsigned char var102;
const unsigned char var103 = 1;
static const unsigned char var104;
static const unsigned char var105 = 1;
extern const unsigned char var106;
extern const unsigned char var107 = 1;
volatile unsigned char var108;
volatile unsigned char var109 = 1;
static volatile unsigned char var110;
static volatile unsigned char var111 = 1;
extern volatile unsigned char var112;
extern volatile unsigned char var113 = 1;
const volatile unsigned char var114;
const volatile unsigned char var115 = 1;
static const volatile unsigned char var116;
static const volatile unsigned char var117 = 1;
extern const volatile unsigned char var118;
extern const volatile unsigned char var119 = 1;
inline unsigned char var120;
inline unsigned char var121 = 1;
static inline unsigned char var122;
static inline unsigned char var123 = 1;
extern inline unsigned char var124;
extern inline unsigned char var125 = 1;
const inline unsigned char var126;
const inline unsigned char var127 = 1;
static const inline unsigned char var128;
static const inline unsigned char var129 = 1;
extern const inline unsigned char var130;
extern const inline unsigned char var131 = 1;
volatile inline unsigned char var132;
volatile inline unsigned char var133 = 1;
static volatile inline unsigned char var134;
static volatile inline unsigned char var135 = 1;
extern volatile inline unsigned char var136;
extern volatile inline unsigned char var137 = 1;
const volatile inline unsigned char var138;
const volatile inline unsigned char var139 = 1;
static const volatile inline unsigned char var140;
static const volatile inline unsigned char var141 = 1;
extern const volatile inline unsigned char var142;
extern const volatile inline unsigned char var143 = 1;

void main() {}
