signed char var48;
signed char var49 = 1;
static signed char var50;
static signed char var51 = 1;
extern signed char var52;
extern signed char var53 = 1;
const signed char var54;
const signed char var55 = 1;
static const signed char var56;
static const signed char var57 = 1;
extern const signed char var58;
extern const signed char var59 = 1;
volatile signed char var60;
volatile signed char var61 = 1;
static volatile signed char var62;
static volatile signed char var63 = 1;
extern volatile signed char var64;
extern volatile signed char var65 = 1;
const volatile signed char var66;
const volatile signed char var67 = 1;
static const volatile signed char var68;
static const volatile signed char var69 = 1;
extern const volatile signed char var70;
extern const volatile signed char var71 = 1;
inline signed char var72;
inline signed char var73 = 1;
static inline signed char var74;
static inline signed char var75 = 1;
extern inline signed char var76;
extern inline signed char var77 = 1;
const inline signed char var78;
const inline signed char var79 = 1;
static const inline signed char var80;
static const inline signed char var81 = 1;
extern const inline signed char var82;
extern const inline signed char var83 = 1;
volatile inline signed char var84;
volatile inline signed char var85 = 1;
static volatile inline signed char var86;
static volatile inline signed char var87 = 1;
extern volatile inline signed char var88;
extern volatile inline signed char var89 = 1;
const volatile inline signed char var90;
const volatile inline signed char var91 = 1;
static const volatile inline signed char var92;
static const volatile inline signed char var93 = 1;
extern const volatile inline signed char var94;
extern const volatile inline signed char var95 = 1;

void main() {}
