short int var240;
short int var241 = 1;
static short int var242;
static short int var243 = 1;
extern short int var244;
extern short int var245 = 1;
const short int var246;
const short int var247 = 1;
static const short int var248;
static const short int var249 = 1;
extern const short int var250;
extern const short int var251 = 1;
volatile short int var252;
volatile short int var253 = 1;
static volatile short int var254;
static volatile short int var255 = 1;
extern volatile short int var256;
extern volatile short int var257 = 1;
const volatile short int var258;
const volatile short int var259 = 1;
static const volatile short int var260;
static const volatile short int var261 = 1;
extern const volatile short int var262;
extern const volatile short int var263 = 1;
inline short int var264;
inline short int var265 = 1;
static inline short int var266;
static inline short int var267 = 1;
extern inline short int var268;
extern inline short int var269 = 1;
const inline short int var270;
const inline short int var271 = 1;
static const inline short int var272;
static const inline short int var273 = 1;
extern const inline short int var274;
extern const inline short int var275 = 1;
volatile inline short int var276;
volatile inline short int var277 = 1;
static volatile inline short int var278;
static volatile inline short int var279 = 1;
extern volatile inline short int var280;
extern volatile inline short int var281 = 1;
const volatile inline short int var282;
const volatile inline short int var283 = 1;
static const volatile inline short int var284;
static const volatile inline short int var285 = 1;
extern const volatile inline short int var286;
extern const volatile inline short int var287 = 1;

void main() {}
