signed long long int var1104;
signed long long int var1105 = 1;
static signed long long int var1106;
static signed long long int var1107 = 1;
extern signed long long int var1108;
extern signed long long int var1109 = 1;
const signed long long int var1110;
const signed long long int var1111 = 1;
static const signed long long int var1112;
static const signed long long int var1113 = 1;
extern const signed long long int var1114;
extern const signed long long int var1115 = 1;
volatile signed long long int var1116;
volatile signed long long int var1117 = 1;
static volatile signed long long int var1118;
static volatile signed long long int var1119 = 1;
extern volatile signed long long int var1120;
extern volatile signed long long int var1121 = 1;
const volatile signed long long int var1122;
const volatile signed long long int var1123 = 1;
static const volatile signed long long int var1124;
static const volatile signed long long int var1125 = 1;
extern const volatile signed long long int var1126;
extern const volatile signed long long int var1127 = 1;
inline signed long long int var1128;
inline signed long long int var1129 = 1;
static inline signed long long int var1130;
static inline signed long long int var1131 = 1;
extern inline signed long long int var1132;
extern inline signed long long int var1133 = 1;
const inline signed long long int var1134;
const inline signed long long int var1135 = 1;
static const inline signed long long int var1136;
static const inline signed long long int var1137 = 1;
extern const inline signed long long int var1138;
extern const inline signed long long int var1139 = 1;
volatile inline signed long long int var1140;
volatile inline signed long long int var1141 = 1;
static volatile inline signed long long int var1142;
static volatile inline signed long long int var1143 = 1;
extern volatile inline signed long long int var1144;
extern volatile inline signed long long int var1145 = 1;
const volatile inline signed long long int var1146;
const volatile inline signed long long int var1147 = 1;
static const volatile inline signed long long int var1148;
static const volatile inline signed long long int var1149 = 1;
extern const volatile inline signed long long int var1150;
extern const volatile inline signed long long int var1151 = 1;

void main() {}
