signed short int var288;
signed short int var289 = 1;
static signed short int var290;
static signed short int var291 = 1;
extern signed short int var292;
extern signed short int var293 = 1;
const signed short int var294;
const signed short int var295 = 1;
static const signed short int var296;
static const signed short int var297 = 1;
extern const signed short int var298;
extern const signed short int var299 = 1;
volatile signed short int var300;
volatile signed short int var301 = 1;
static volatile signed short int var302;
static volatile signed short int var303 = 1;
extern volatile signed short int var304;
extern volatile signed short int var305 = 1;
const volatile signed short int var306;
const volatile signed short int var307 = 1;
static const volatile signed short int var308;
static const volatile signed short int var309 = 1;
extern const volatile signed short int var310;
extern const volatile signed short int var311 = 1;
inline signed short int var312;
inline signed short int var313 = 1;
static inline signed short int var314;
static inline signed short int var315 = 1;
extern inline signed short int var316;
extern inline signed short int var317 = 1;
const inline signed short int var318;
const inline signed short int var319 = 1;
static const inline signed short int var320;
static const inline signed short int var321 = 1;
extern const inline signed short int var322;
extern const inline signed short int var323 = 1;
volatile inline signed short int var324;
volatile inline signed short int var325 = 1;
static volatile inline signed short int var326;
static volatile inline signed short int var327 = 1;
extern volatile inline signed short int var328;
extern volatile inline signed short int var329 = 1;
const volatile inline signed short int var330;
const volatile inline signed short int var331 = 1;
static const volatile inline signed short int var332;
static const volatile inline signed short int var333 = 1;
extern const volatile inline signed short int var334;
extern const volatile inline signed short int var335 = 1;

void main() {}
