signed long var720;
signed long var721 = 1;
static signed long var722;
static signed long var723 = 1;
extern signed long var724;
extern signed long var725 = 1;
const signed long var726;
const signed long var727 = 1;
static const signed long var728;
static const signed long var729 = 1;
extern const signed long var730;
extern const signed long var731 = 1;
volatile signed long var732;
volatile signed long var733 = 1;
static volatile signed long var734;
static volatile signed long var735 = 1;
extern volatile signed long var736;
extern volatile signed long var737 = 1;
const volatile signed long var738;
const volatile signed long var739 = 1;
static const volatile signed long var740;
static const volatile signed long var741 = 1;
extern const volatile signed long var742;
extern const volatile signed long var743 = 1;
inline signed long var744;
inline signed long var745 = 1;
static inline signed long var746;
static inline signed long var747 = 1;
extern inline signed long var748;
extern inline signed long var749 = 1;
const inline signed long var750;
const inline signed long var751 = 1;
static const inline signed long var752;
static const inline signed long var753 = 1;
extern const inline signed long var754;
extern const inline signed long var755 = 1;
volatile inline signed long var756;
volatile inline signed long var757 = 1;
static volatile inline signed long var758;
static volatile inline signed long var759 = 1;
extern volatile inline signed long var760;
extern volatile inline signed long var761 = 1;
const volatile inline signed long var762;
const volatile inline signed long var763 = 1;
static const volatile inline signed long var764;
static const volatile inline signed long var765 = 1;
extern const volatile inline signed long var766;
extern const volatile inline signed long var767 = 1;

void main() {}
