int var0();
static int var1();
extern int var2();
const int var3();
volatile int var4();
inline int var5();
const static int var6();
volatile static int var7();
inline static int var8();
const extern int var9();
volatile extern int var10();
inline extern int var11();
static const int var12();
extern const int var13();
volatile const int var14();
inline const int var15();
static volatile int var16();
extern volatile int var17();
const volatile int var18();
inline volatile int var19();
static inline int var20();
extern inline int var21();
const inline int var22();
volatile inline int var23();
volatile const static int var24();
inline const static int var25();
const volatile static int var26();
inline volatile static int var27();
const inline static int var28();
volatile inline static int var29();
volatile const extern int var30();
inline const extern int var31();
const volatile extern int var32();
inline volatile extern int var33();
const inline extern int var34();
volatile inline extern int var35();
volatile static const int var36();
inline static const int var37();
volatile extern const int var38();
inline extern const int var39();
static volatile const int var40();
extern volatile const int var41();
inline volatile const int var42();
static inline const int var43();
extern inline const int var44();
volatile inline const int var45();
const static volatile int var46();
inline static volatile int var47();
const extern volatile int var48();
inline extern volatile int var49();
static const volatile int var50();
extern const volatile int var51();
inline const volatile int var52();
static inline volatile int var53();
extern inline volatile int var54();
const inline volatile int var55();
const static inline int var56();
volatile static inline int var57();
const extern inline int var58();
volatile extern inline int var59();
static const inline int var60();
extern const inline int var61();
volatile const inline int var62();
static volatile inline int var63();
extern volatile inline int var64();
const volatile inline int var65();
inline volatile const static int var66();
volatile inline const static int var67();
inline const volatile static int var68();
const inline volatile static int var69();
volatile const inline static int var70();
const volatile inline static int var71();
inline volatile const extern int var72();
volatile inline const extern int var73();
inline const volatile extern int var74();
const inline volatile extern int var75();
volatile const inline extern int var76();
const volatile inline extern int var77();
inline volatile static const int var78();
volatile inline static const int var79();
inline volatile extern const int var80();
volatile inline extern const int var81();
inline static volatile const int var82();
inline extern volatile const int var83();
static inline volatile const int var84();
extern inline volatile const int var85();
volatile static inline const int var86();
volatile extern inline const int var87();
static volatile inline const int var88();
extern volatile inline const int var89();
inline const static volatile int var90();
const inline static volatile int var91();
inline const extern volatile int var92();
const inline extern volatile int var93();
inline static const volatile int var94();
inline extern const volatile int var95();
static inline const volatile int var96();
extern inline const volatile int var97();
const static inline volatile int var98();
const extern inline volatile int var99();
static const inline volatile int var100();
extern const inline volatile int var101();
volatile const static inline int var102();
const volatile static inline int var103();
volatile const extern inline int var104();
const volatile extern inline int var105();
volatile static const inline int var106();
volatile extern const inline int var107();
static volatile const inline int var108();
extern volatile const inline int var109();
const static volatile inline int var110();
const extern volatile inline int var111();
static const volatile inline int var112();
extern const volatile inline int var113();

void main() {}
