#include <stdio.h>

double d1 = +0;
double d2 = -0;
double d3 = 1.0 / 3.0;
double d4 = 0.1 + 0.2;
double d5 = -1.0 / 3.0;
double d6 = -0.1 - 0.2;
double d7 = 1;
double d8 = 4.5;
double d9 = 5.89999961;
double d10 = -10.2349961;
double d11 = 2432423422341;
double d12 = -32434324234;
double d13 = 0;//= 1.0 / 0.0;
double d14 = 0;//= -1.0 / 0.0;
double d15 = 0;//= 0.0 / 0.0;

int i1 = 0;
int i2 = 523432;
int i3 = -346534;
int i4 = -2342;
int i5 = 2147483647;
int i6 = -2147483647;
int i7 = 4324;
int i8 = 3244534;
int i9 = 5147483647;
int i10 = -5147483647;

int main() {
    long long i = 0;
    double x;
    x = (double)d1;
    printf("%f\n", x);
    i = 1;
    printf("%lld\n", i);
    x = (double)d2;
    printf("%f\n", x);
    i = 2;
    printf("%lld\n", i);
    x = (double)d3;
    printf("%f\n", x);
    i = 3;
    printf("%lld\n", i);
    x = (double)d4;
    printf("%f\n", x);
    i = 4;
    printf("%lld\n", i);
    x = (double)d5;
    printf("%f\n", x);
    i = 5;
    printf("%lld\n", i);
    x = (double)d6;
    printf("%f\n", x);
    i = 6;
    printf("%lld\n", i);
    x = (double)d7;
    printf("%f\n", x);
    i = 7;
    printf("%lld\n", i);
    x = (double)d8;
    printf("%f\n", x);
    i = 8;
    printf("%lld\n", i);
    x = (double)d9;
    printf("%f\n", x);
    i = 9;
    printf("%lld\n", i);
    x = (double)d10;
    printf("%f\n", x);
    i = 10;
    printf("%lld\n", i);
    x = (double)d11;
    printf("%f\n", x);
    i = 11;
    printf("%lld\n", i);
    x = (double)d12;
    printf("%f\n", x);
    i = 12;
    printf("%lld\n", i);
    x = (double)d13;
    printf("%f\n", x);
    i = 13;
    printf("%lld\n", i);
    x = (double)d14;
    printf("%f\n", x);
    i = 14;
    printf("%lld\n", i);
    x = (double)d15;
    printf("%f\n", x);
    i = 15;
    printf("%lld\n", i);
    x = (double)i1;
    printf("%f\n", x);
    i = 16;
    printf("%lld\n", i);
    x = (double)i2;
    printf("%f\n", x);
    i = 17;
    printf("%lld\n", i);
    x = (double)i3;
    printf("%f\n", x);
    i = 18;
    printf("%lld\n", i);
    x = (double)i4;
    printf("%f\n", x);
    i = 19;
    printf("%lld\n", i);
    x = (double)i5;
    printf("%f\n", x);
    i = 20;
    printf("%lld\n", i);
    x = (double)i6;
    printf("%f\n", x);
    i = 21;
    printf("%lld\n", i);
    x = (double)i7;
    printf("%f\n", x);
    i = 22;
    printf("%lld\n", i);
    x = (double)i8;
    printf("%f\n", x);
    i = 23;
    printf("%lld\n", i);
    x = (double)i9;
    printf("%f\n", x);
    i = 24;
    printf("%lld\n", i);
    x = (double)i10;
    printf("%f\n", x);
    i = 25;
    printf("%lld\n", i);
}
