#include <stdio.h>

double d1 = +0;
double d2 = -0;
double d3 = 1.0 / 3.0;
double d4 = 0.1 + 0.2;
double d5 = -1.0 / 3.0;
double d6 = -0.1 - 0.2;
double d7 = 1;
double d8 = 4.5;
double d9 = 5.89999961;
double d10 = -10.2349961;
double d11 = 2432423422341;
double d12 = -32434324234;
double d13 = 0;//= 1.0 / 0.0;
double d14 = 0;//= -1.0 / 0.0;
double d15 = 0;//= 0.0 / 0.0;

int i1 = 0;
int i2 = 523432;
int i3 = -346534;
int i4 = -2342;
int i5 = 2147483647;
int i6 = -2147483647;
int i7 = 4324;
int i8 = 3244534;
int i9 = 5147483647;
int i10 = -5147483647;

long long ll1 = 0;
long long ll2 = 72036854775807;
long long ll3 = -922337220368;
long long ll4 = 234;
long long ll5 = 9223372036854775807;
long long ll6 = -9223372036854775807;

short s1 = 0;
short s2 = 3276;
short s3 = -2276;
short s4 = 234; 
short s5 = -334;
short s6 = 32767;
short s7 = -32767;
short s8 = 52767;
short s9 = -52767;

unsigned int ui1 = 0;
unsigned int ui2 = 523432;
unsigned int ui3 = 4294967295;
unsigned int ui4 = 6294967295;
unsigned int ui5 = -1233;

unsigned short us1 = 0;
unsigned short us2 = 65535;
unsigned short us3 = 85535;
unsigned short us4 = -3242;
unsigned short us5 = 3425;

int main() {
    long long i = 0;
    unsigned int x;
    x = (unsigned int)d1;
    printf("%u\n", x);
    i = 1;
    printf("%lld\n", i);
    x = (unsigned int)d2;
    printf("%u\n", x);
    i = 2;
    printf("%lld\n", i);
    x = (unsigned int)d3;
    printf("%u\n", x);
    i = 3;
    printf("%lld\n", i);
    x = (unsigned int)d4;
    printf("%u\n", x);
    i = 4;
    printf("%lld\n", i);
    x = (unsigned int)d5;
    printf("%u\n", x);
    i = 5;
    printf("%lld\n", i);
    x = (unsigned int)d6;
    printf("%u\n", x);
    i = 6;
    printf("%lld\n", i);
    x = (unsigned int)d7;
    printf("%u\n", x);
    i = 7;
    printf("%lld\n", i);
    x = (unsigned int)d8;
    printf("%u\n", x);
    i = 8;
    printf("%lld\n", i);
    x = (unsigned int)d9;
    printf("%u\n", x);
    i = 9;
    printf("%lld\n", i);
    x = (unsigned int)d10;
    printf("%u\n", x);
    i = 10;
    printf("%lld\n", i);
    x = (unsigned int)d11;
    printf("%u\n", x);
    i = 11;
    printf("%lld\n", i);
    x = (unsigned int)d12;
    printf("%u\n", x);
    i = 12;
    printf("%lld\n", i);
    x = (unsigned int)d13;
    printf("%u\n", x);
    i = 13;
    printf("%lld\n", i);
    x = (unsigned int)d14;
    printf("%u\n", x);
    i = 14;
    printf("%lld\n", i);
    x = (unsigned int)d15;
    printf("%u\n", x);
    i = 15;
    printf("%lld\n", i);
    x = (unsigned int)i1;
    printf("%u\n", x);
    i = 16;
    printf("%lld\n", i);
    x = (unsigned int)i2;
    printf("%u\n", x);
    i = 17;
    printf("%lld\n", i);
    x = (unsigned int)i3;
    printf("%u\n", x);
    i = 18;
    printf("%lld\n", i);
    x = (unsigned int)i4;
    printf("%u\n", x);
    i = 19;
    printf("%lld\n", i);
    x = (unsigned int)i5;
    printf("%u\n", x);
    i = 20;
    printf("%lld\n", i);
    x = (unsigned int)i6;
    printf("%u\n", x);
    i = 21;
    printf("%lld\n", i);
    x = (unsigned int)i7;
    printf("%u\n", x);
    i = 22;
    printf("%lld\n", i);
    x = (unsigned int)i8;
    printf("%u\n", x);
    i = 23;
    printf("%lld\n", i);
    x = (unsigned int)i9;
    printf("%u\n", x);
    i = 24;
    printf("%lld\n", i);
    x = (unsigned int)i10;
    printf("%u\n", x);
    i = 25;
    printf("%lld\n", i);
    x = (unsigned int)ll1;
    printf("%u\n", x);
    i = 26;
    printf("%lld\n", i);
    x = (unsigned int)ll2;
    printf("%u\n", x);
    i = 27;
    printf("%lld\n", i);
    x = (unsigned int)ll3;
    printf("%u\n", x);
    i = 28;
    printf("%lld\n", i);
    x = (unsigned int)ll4;
    printf("%u\n", x);
    i = 29;
    printf("%lld\n", i);
    x = (unsigned int)ll5;
    printf("%u\n", x);
    i = 30;
    printf("%lld\n", i);
    x = (unsigned int)ll6;
    printf("%u\n", x);
    i = 31;
    printf("%lld\n", i);
    x = (unsigned int)s1;
    printf("%u\n", x);
    i = 32;
    printf("%lld\n", i);
    x = (unsigned int)s2;
    printf("%u\n", x);
    i = 33;
    printf("%lld\n", i);
    x = (unsigned int)s3;
    printf("%u\n", x);
    i = 34;
    printf("%lld\n", i);
    x = (unsigned int)s4;
    printf("%u\n", x);
    i = 35;
    printf("%lld\n", i);
    x = (unsigned int)s5;
    printf("%u\n", x);
    i = 36;
    printf("%lld\n", i);
    x = (unsigned int)s6;
    printf("%u\n", x);
    i = 37;
    printf("%lld\n", i);
    x = (unsigned int)s7;
    printf("%u\n", x);
    i = 38;
    printf("%lld\n", i);
    x = (unsigned int)s8;
    printf("%u\n", x);
    i = 39;
    printf("%lld\n", i);
    x = (unsigned int)s9;
    printf("%u\n", x);
    i = 40;
    printf("%lld\n", i);
    x = (unsigned int)ui1;
    printf("%u\n", x);
    i = 41;
    printf("%lld\n", i);
    x = (unsigned int)ui2;
    printf("%u\n", x);
    i = 42;
    printf("%lld\n", i);
    x = (unsigned int)ui3;
    printf("%u\n", x);
    i = 43;
    printf("%lld\n", i);
    x = (unsigned int)ui4;
    printf("%u\n", x);
    i = 44;
    printf("%lld\n", i);
    x = (unsigned int)ui5;
    printf("%u\n", x);
    i = 45;
    printf("%lld\n", i);
    x = (unsigned int)us1;
    printf("%u\n", x);
    i = 46;
    printf("%lld\n", i);
    x = (unsigned int)us2;
    printf("%u\n", x);
    i = 47;
    printf("%lld\n", i);
    x = (unsigned int)us3;
    printf("%u\n", x);
    i = 48;
    printf("%lld\n", i);
    x = (unsigned int)us4;
    printf("%u\n", x);
    i = 49;
    printf("%lld\n", i);
    x = (unsigned int)us5;
    printf("%u\n", x);
    i = 50;
    printf("%lld\n", i);
}
