#include <stdio.h>

long long ll1 = 0;
long long ll2 = 72036854775807;
long long ll3 = -922337220368;
long long ll4 = 234;
long long ll5 = 9223372036854775807;
long long ll6 = -9223372036854775807;

short s1 = 0;
short s2 = 3276;
short s3 = -2276;
short s4 = 234;
short s5 = -334;
short s6 = 32767;
short s7 = -32767;
short s8 = 52767;
short s9 = -52767;

unsigned int ui1 = 0;
unsigned int ui2 = 523432;
unsigned int ui3 = 4294967295;
unsigned int ui4 = 6294967295;
unsigned int ui5 = -1233;

unsigned short us1 = 0;
unsigned short us2 = 65535;
unsigned short us3 = 85535;
unsigned short us4 = -3242;
unsigned short us5 = 3425;

int main() {
    unsigned short int x;
    long long i = 0;
    x = (unsigned short int)ll1;
    printf("%hu\n", x);
    i = 26;
    printf("%lld\n", i);
    x = (unsigned short int)ll2;
    printf("%hu\n", x);
    i = 27;
    printf("%lld\n", i);
    x = (unsigned short int)ll3;
    printf("%hu\n", x);
    i = 28;
    printf("%lld\n", i);
    x = (unsigned short int)ll4;
    printf("%hu\n", x);
    i = 29;
    printf("%lld\n", i);
    x = (unsigned short int)ll5;
    printf("%hu\n", x);
    i = 30;
    printf("%lld\n", i);
    x = (unsigned short int)ll6;
    printf("%hu\n", x);
    i = 31;
    printf("%lld\n", i);
    x = (unsigned short int)s1;
    printf("%hu\n", x);
    i = 32;
    printf("%lld\n", i);
    x = (unsigned short int)s2;
    printf("%hu\n", x);
    i = 33;
    printf("%lld\n", i);
    x = (unsigned short int)s3;
    printf("%hu\n", x);
    i = 34;
    printf("%lld\n", i);
    x = (unsigned short int)s4;
    printf("%hu\n", x);
    i = 35;
    printf("%lld\n", i);
    x = (unsigned short int)s5;
    printf("%hu\n", x);
    i = 36;
    printf("%lld\n", i);
    x = (unsigned short int)s6;
    printf("%hu\n", x);
    i = 37;
    printf("%lld\n", i);
    x = (unsigned short int)s7;
    printf("%hu\n", x);
    i = 38;
    printf("%lld\n", i);
    x = (unsigned short int)s8;
    printf("%hu\n", x);
    i = 39;
    printf("%lld\n", i);
    x = (unsigned short int)s9;
    printf("%hu\n", x);
    i = 40;
    printf("%lld\n", i);
    x = (unsigned short int)ui1;
    printf("%hu\n", x);
    i = 41;
    printf("%lld\n", i);
    x = (unsigned short int)ui2;
    printf("%hu\n", x);
    i = 42;
    printf("%lld\n", i);
    x = (unsigned short int)ui3;
    printf("%hu\n", x);
    i = 43;
    printf("%lld\n", i);
    x = (unsigned short int)ui4;
    printf("%hu\n", x);
    i = 44;
    printf("%lld\n", i);
    x = (unsigned short int)ui5;
    printf("%hu\n", x);
    i = 45;
    printf("%lld\n", i);
    x = (unsigned short int)us1;
    printf("%hu\n", x);
    i = 46;
    printf("%lld\n", i);
    x = (unsigned short int)us2;
    printf("%hu\n", x);
    i = 47;
    printf("%lld\n", i);
    x = (unsigned short int)us3;
    printf("%hu\n", x);
    i = 48;
    printf("%lld\n", i);
    x = (unsigned short int)us4;
    printf("%hu\n", x);
    i = 49;
    printf("%lld\n", i);
    x = (unsigned short int)us5;
    printf("%hu\n", x);
    i = 50;
    printf("%lld\n", i);
}
