# SPDX-FileCopyrightText: Copyright (c) 2021-2022 Polystat.org
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: csmith

'on':
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

concurrency:
  group: csmith-${{ github.ref }}
  cancel-in-progress: true

jobs:
  csmith:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - uses: ./.github/actions/llvm

      - name: Install csmith
        run: |
          cd ..
          git clone https://github.com/csmith-project/csmith.git
          cd csmith
          cmake -DCMAKE_INSTALL_PREFIX=csmith .
          make

      - name: Generating tests
        run: |
          cd ./scripts
          python3 csmith.py -h
          python3 csmith.py ../tests/main/csmith -c 100

      - name: Testing
        run: |
          cd ./scripts
          python3 transpile.py -h
          python3 transpile.py ../tests/main/csmith -n

      - name: Clean test directory
        run: cd ./scripts && python3 clean_before_transpilation.py -p ../tests/main/csmith

      - name: Make archive from csmith tests
        run: tar -cf csmith.tar.gz ./tests/main/csmith

      - uses: actions/upload-artifact@v4
        with:
          name: csmith
          path: csmith.tar.gz
