# SPDX-FileCopyrightText: Copyright (c) 2021-2022 c2eo team
# SPDX-License-Identifier: MIT
---
name: reuse
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: reuse-${{ github.ref }}
  cancel-in-progress: true
jobs:
  reuse:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: fsfe/reuse-action@v6
