# SPDX-FileCopyrightText: Copyright (c) 2021-2022 c2eo team
# SPDX-License-Identifier: MIT
---
name: statistics

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: statistics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc-c-torture:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ./.github/actions/llvm

      - name: Download gcc-c-torture
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "polystat/c2eo"
          tag: "0.1.16"
          fileName: "gcc.c-torture.tar.gz"

      - name: Unpack gcc-c-torture
        run: tar -xvf gcc.c-torture.tar.gz -C . > /dev/null

      - name: Compilation
        run: |
          cd ./scripts
          python3 compile.py -h
          python3 compile.py -p ../gcc.c-torture -s gcc-compile -n -i -r 100
